[tools]
bun = "1.4.2"
go = "1.27.1"
node = "24.21.0"
python = "3.14.8"
ruby = "4.0.7"
rust = "1.99.0"
terraform = "1.16.4"

"npm:opensrc" = "0.7.3"
"npm:pinpm" = "0.4.1"
"npm:pnpm" = "11.28.3"
"npm:sfw" = "2.0.6"
"npm:swampman" = "0.0.2"
"npm:@codize/cli" = "0.7.0"
"npm:@fission-ai/openspec" = "1.14.0"

"aqua:anthropics/claude-code" = "2.1.293"
"aqua:evilmartians/lefthook" = "2.1.16"

"github:microsoft/apm" = "0.32.0"
"github:vercel-labs/fx" = "latest"

[settings]
experimental = true
hook_env.chpwd_only = true
idiomatic_version_file_enable_tools = ["node", "terraform"]
