[tools]
bun = "1.2.18"
go = "1.26.1"
node = "24.14.1"
python = "3.14.3"
ruby = "4.0.2"
rust = "1.94.1"
terraform = "1.13.0"

# go tools
"go:github.com/chrishrb/go-grip" = "0.8.0"

# npm packages
"npm:renovate" = "43.104.7"
"npm:mmcp" = "0.6.2"
"npm:pinpm" = "0.4.1"
"npm:sfw" = "2.0.4"
"npm:@google/gemini-cli" = "0.36.0"
"npm:@codize/cli" = "0.6.0"

# ruby gems
"gem:xvert" = "0.4.0"

# pipx packages
"pipx:git+https://github.com/koki-develop/git-aicommit.git" = "v0.14.1"

# aqua packages
"aqua:anthropics/claude-code" = "2.1.92"

[settings]
experimental = true
hook_env.chpwd_only = true
idiomatic_version_file_enable_tools = ["node", "terraform"]
