# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  pull:
    cmds:
      - git pull origin main
  diff:
    aliases: [d]
    deps: [pull]
    cmds:
      - chezmoi diff
  apply:
    aliases: [a]
    deps: [pull]
    cmds:
      - chezmoi apply -v
