# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - git pull origin main
      - chezmoi apply -v
      - brew bundle --global
      - brew upgrade
