# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - dcli sync
      - git pull origin main
      - chezmoi apply -v
      - task: update
      - dcli logout

  update:
    cmds:
      - brew bundle --global
      - brew upgrade
