# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - dcli sync
      - git pull origin main
      - chezmoi apply -v
      - task: update
      - dcli logout

  update:
    cmds:
      - task: update-nvim-plugins
      - task: update-brew-formula
      - task: update-zplug-packages

  update-nvim-plugins:
    cmds:
      - nvim +PlugUpdate +qall

  update-zplug-packages:
    cmds:
      - zsh --interactive -c 'zplug update'

  update-brew-formula:
    cmds:
      - brew update
      - brew bundle --global
      - brew upgrade
