# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - echo 'this-device persistent-login on' | keeper --batch-mode shell
      - git fetch
      - git rebase origin/main
      - chezmoi apply -v
      - task: update

  update:
    cmds:
      - task: update-nvim-plugins
      - task: update-brew-formula
      - task: update-zplug-packages
      - mise install

  update-nvim-plugins:
    cmds:
      - nvim +PlugUpdate +qall

  update-zplug-packages:
    cmds:
      - zsh -c '. ~/.zplug/init.zsh && zplug update'

  update-brew-formula:
    cmds:
      - brew update
      - brew bundle --global
      - brew upgrade
