# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - keeper shell
      - git fetch
      - git rebase origin/main
      - chezmoi apply -v
      - task: update

  update:
    cmds:
      - task: update-brew-formula
      - task: update-zinit-packages
      - mise install

  update-zinit-packages:
    cmds:
      - zsh -c '. ~/.local/share/zinit/zinit.git/zinit.zsh && zinit update'

  update-brew-formula:
    cmds:
      - brew update
      - brew bundle --global
      - brew upgrade

  update-completions:
    cmds:
      - mkdir -p ~/.zsh/completion
      - codex completion zsh > ~/.zsh/completion/_codex
      - pinact completion zsh > ~/.zsh/completion/_pinact
      - usage generate completion zsh --file ./completions/aws-vault.kdl aws-vault > ~/.zsh/completion/_aws-vault
