# !/bin/zsh -e

# prompt
precmd() { printf '\n' }
setopt PROMPT_SUBST
source ~/dotfiles/src/zsh/git-prompt.sh
export PROMPT=$'%* [%n@%m: %F{green}%~%f]%F{yellow}$(__git_ps1 " (%s)")%f\n\$ '

# zsh-completions
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
autoload -Uz compinit
compinit

# language
export LANG=ja_JP.UTF-8

# history
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=1000
export SAVEHIST=1000

# asdf
. $(brew --prefix asdf)/libexec/asdf.sh
