# !/bin/zsh -e

setopt autocd
setopt magic_equal_subst
setopt hist_ignore_dups
setopt no_beep
setopt no_histbeep
setopt no_listbeep

# prompt
precmd() { printf '\n' }
setopt prompt_subst
source ~/dotfiles/src/zsh/git-prompt.sh
export PROMPT=$'%* [%n@%m: %F{green}%~%f]%F{yellow}$(__git_ps1 " (%s)")%f\n\$ '

# zsh-completions
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
autoload -Uz compinit
compinit

zstyle ':completion:*:default' menu select=2

# language
export LANG=ja_JP.UTF-8

# history
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=1000
export SAVEHIST=1000

# asdf
. $(brew --prefix asdf)/libexec/asdf.sh

# alias - git
alias g='git'
alias gad='git add'
alias gcom='git commit -m'
alias gcomv='git commit -v'
alias gdi='git diff'
alias glo='git log --pretty=oneline'
alias gst='git status'
alias gre='git reset'
alias gdem="git branch --merged|egrep -v '\*|develop|master|main'|xargs git branch -d"

# alias - grep
alias grep='grep --color=auto'

# ls
alias l='exa -1'
alias la='exa -1a'
alias ll='exa -l'
alias lla='exa -al'

# mkdir
alias mkdir='mkdir -p'

# mv
alias mv='mv -i'

# rm
alias rm='trash-put'

# vi
alias v='nvim'
alias vi='nvim'
