onboarding = false

[theme]
name = "terminal"

[keys]
prefix = "ctrl+q"
navigate_workspace_up = ["up", "k"]
navigate_workspace_down = ["down", "j"]
navigate_pane_down = "shift+j"
navigate_pane_up = "shift+k"

[[keys.command]]
key = "prefix+!"
type = "shell"
command = '"$HERDR_BIN_PATH" pane move "$HERDR_ACTIVE_PANE_ID" --new-tab --focus'
description = "break pane to new tab"

[[keys.command]]
key = "prefix+m"
type = "popup"
command = "~/.config/herdr/scripts/move-pane-to-tab.sh"
description = "move pane to tab"

[ui]
copy_on_select = false
prompt_new_tab_name = false
tab_bar_right = [
  { type = "datetime", format = "%Y-%m-%d %H:%M" },
]

[ui.toast]
delivery = "terminal"

[ui.toast.clipboard]
enabled = false

[experimental]
reveal_hidden_cursor_for_cjk_ime = true
cjk_ime_agents = ["claude", "codex"]
switch_ascii_input_source_in_prefix = true
