#!/usr/bin/env zsh

case "$1" in
    add)
        if [[ -z "$2" ]]; then
            echo "Usage: git-wkt add <branch_name>"
            exit 1
        fi
        branch_name="$2"
        git worktree add .git/git-wkt/worktrees/"$branch_name" -b "$branch_name"
        ;;
    rm)
        if [[ -z "$2" ]]; then
            echo "Usage: git-wkt rm <branch_name>"
            exit 1
        fi
        branch_name="$2"
        git worktree remove .git/git-wkt/worktrees/"$branch_name"
        ;;
    ls)
        if [[ -d .git/git-wkt/worktrees ]]; then
            for dir in .git/git-wkt/worktrees/*/; do
                if [[ -d "$dir" ]]; then
                    basename "$dir"
                fi
            done
        fi
        ;;
    *)
        echo "Usage: git-wkt {add|rm|ls} <branch_name>"
        exit 1
        ;;
esac
